### ISSUE TITLE
Remove generic styling

### ISSUE THREAD

**Issue by leeandher** [leeandher/leander.xyz#68]
Ensure that there are no styled components w/o using classnames, this can cause unwanted css aversion:

**Avoid**:
```css
const Wrapper = styled.div`
  margin: 0;
  h1 {
    margin: 2rem;  
  }
`
```
**Prefer**:
```css
const Wrapper = styled.div`
  margin: 0;
  .header {
    margin: 2rem;  
  }
`
```
